// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.8.6-316-g0707b4be-dirty"
#define MICROPY_GIT_HASH "0707b4be-dirty"
#define MICROPY_BUILD_DATE "2017-05-11"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (8)
#define MICROPY_VERSION_MICRO (6)
#define MICROPY_VERSION_STRING "1.8.6"
