// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.8.6"
#define MICROPY_GIT_HASH "<no hash>"
#define MICROPY_BUILD_DATE "2017-05-25"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (8)
#define MICROPY_VERSION_MICRO (6)
#define MICROPY_VERSION_STRING "1.8.6"
