// This file was automatically generated by make-pins.py
//
// --af boards/mk64_af.csv
// --board boards/TEENSY_3.5/pins.csv
// --prefix boards/mk20dx256_prefix.c

// stm32fxx-prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <mk20dx128.h>

#include "py/obj.h"
#include "teensy_hal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .af_fn = (af_ptr) \
}

#define PIN(p_port, p_pin, p_num_af, p_af) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (p_num_af), \
    .pin_mask = (1 << (p_pin)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = 0, \
    .adc_channel = 0, \
}

const pin_af_obj_t pin_E0_af[] = {
  AF( 0, ADC     ,  1, SE4a      , ADC1    ), // ADC1_SE4a
  //( 1, PTE     ,  0,           , PTE0    ), // PTE0
  //( 2, SPI     ,  1, PCS1      , SPI1    ), // SPI1_PCS1
  AF( 3, UART    ,  1, TX        , UART1   ), // UART1_TX
  //( 4, SDHC    ,  0, D1        , SDHC0   ), // SDHC0_D1
  //( 5, TRACE   ,  0, CLKOUT    , TRACE   ), // TRACE_CLKOUT
  AF( 6, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  //( 7, RTC     ,  0, CLKOUT    , RTC     ), // RTC_CLKOUT
};

const pin_obj_t pin_E0 = PIN(E, 0, 3, pin_E0_af);

const pin_af_obj_t pin_E1_af[] = {
  AF( 0, ADC     ,  1, SE5a      , ADC1    ), // ADC1_SE5a
  //( 1, PTE     ,  1,           , PTE1    ), // PTE1
  //( 1, LLWU    ,  0, P0        , LLWU    ), // LLWU_P0
  //( 2, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
  AF( 3, UART    ,  1, RX        , UART1   ), // UART1_RX
  //( 4, SDHC    ,  0, D0        , SDHC0   ), // SDHC0_D0
  //( 5, TRACE   ,  0, D3        , TRACE   ), // TRACE_D3
  AF( 6, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  //( 7, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
};

const pin_obj_t pin_E1 = PIN(E, 1, 3, pin_E1_af);

const pin_af_obj_t pin_E2_af[] = {
  AF( 0, ADC     ,  0, DP2       , ADC0    ), // ADC0_DP2
  AF( 0, ADC     ,  1, SE6a      , ADC1    ), // ADC1_SE6a
  //( 1, PTE     ,  2,           , PTE2    ), // PTE2
  //( 1, LLWU    ,  0, P1        , LLWU    ), // LLWU_P1
  AF( 2, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
  //( 3, UART    ,  1, CTS_b     , UART1   ), // UART1_CTS_b
  //( 4, SDHC    ,  0, DCLK      , SDHC0   ), // SDHC0_DCLK
  //( 5, TRACE   ,  0, D2        , TRACE   ), // TRACE_D2
};

const pin_obj_t pin_E2 = PIN(E, 2, 3, pin_E2_af);

const pin_af_obj_t pin_E3_af[] = {
  //( 0, ADC     ,  0, DM2       , ADC0    ), // ADC0_DM2
  AF( 0, ADC     ,  1, SE7a      , ADC1    ), // ADC1_SE7a
  //( 1, PTE     ,  3,           , PTE3    ), // PTE3
  //( 2, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
  //( 3, UART    ,  1, RTS_b     , UART1   ), // UART1_RTS_b
  //( 4, SDHC    ,  0, CMD       , SDHC0   ), // SDHC0_CMD
  //( 5, TRACE   ,  0, D1        , TRACE   ), // TRACE_D1
  //( 6, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
};

const pin_obj_t pin_E3 = PIN(E, 3, 1, pin_E3_af);

const pin_af_obj_t pin_E4_af[] = {
  //( 1, PTE     ,  4,           , PTE4    ), // PTE4
  //( 1, LLWU    ,  0, P2        , LLWU    ), // LLWU_P2
  //( 2, SPI     ,  1, PCS0      , SPI1    ), // SPI1_PCS0
  AF( 3, UART    ,  3, TX        , UART3   ), // UART3_TX
  //( 4, SDHC    ,  0, D3        , SDHC0   ), // SDHC0_D3
  //( 5, TRACE   ,  0, D0        , TRACE   ), // TRACE_D0
};

const pin_obj_t pin_E4 = PIN(E, 4, 1, pin_E4_af);

const pin_af_obj_t pin_E5_af[] = {
  //( 1, PTE     ,  5,           , PTE5    ), // PTE5
  //( 2, SPI     ,  1, PCS2      , SPI1    ), // SPI1_PCS2
  AF( 3, UART    ,  3, RX        , UART3   ), // UART3_RX
  //( 4, SDHC    ,  0, D2        , SDHC0   ), // SDHC0_D2
  AF( 6, FTM     ,  3, CH0       , FTM3    ), // FTM3_CH0
};

const pin_obj_t pin_E5 = PIN(E, 5, 2, pin_E5_af);

const pin_af_obj_t pin_E10_af[] = {
  //( 1, PTE     , 10,           , PTE10   ), // PTE10
  //( 3, UART    ,  5, CTS_b     , UART5   ), // UART5_CTS_b
  //( 4, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
  AF( 6, FTM     ,  3, CH5       , FTM3    ), // FTM3_CH5
};

const pin_obj_t pin_E10 = PIN(E, 10, 1, pin_E10_af);

const pin_af_obj_t pin_E11_af[] = {
  //( 1, PTE     , 11,           , PTE11   ), // PTE11
  //( 3, UART    ,  5, RTS_b     , UART5   ), // UART5_RTS_b
  //( 4, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  AF( 6, FTM     ,  3, CH6       , FTM3    ), // FTM3_CH6
};

const pin_obj_t pin_E11 = PIN(E, 11, 1, pin_E11_af);

const pin_af_obj_t pin_Z1_af[] = {
  AF( 0, ADC     ,  0, DP1       , ADC0    ), // ADC0_DP1
  //( 1, PTZ     ,  1,           , PTZ1    ), // PTZ1
};

const pin_obj_t pin_Z1 = PIN(Z, 1, 1, pin_Z1_af);

const pin_af_obj_t pin_Z3_af[] = {
  AF( 0, ADC     ,  1, DP1       , ADC1    ), // ADC1_DP1
  //( 1, PTZ     ,  3,           , PTZ3    ), // PTZ3
};

const pin_obj_t pin_Z3 = PIN(Z, 3, 1, pin_Z3_af);

const pin_af_obj_t pin_Z7_af[] = {
  AF( 0, ADC     ,  1, DP0       , ADC1    ), // ADC1_DP0
  AF( 0, ADC     ,  0, DP3       , ADC0    ), // ADC0_DP3
  //( 1, PTZ     ,  7,           , PTZ7    ), // PTZ7
};

const pin_obj_t pin_Z7 = PIN(Z, 7, 2, pin_Z7_af);

const pin_af_obj_t pin_Z8_af[] = {
  AF( 0, ADC     ,  1, DM0       , ADC1    ), // ADC1_DM0
  //( 0, ADC     ,  0, DM3       , ADC0    ), // ADC0_DM3
  //( 1, PTZ     ,  8,           , PTZ8    ), // PTZ8
};

const pin_obj_t pin_Z8 = PIN(Z, 8, 1, pin_Z8_af);

const pin_af_obj_t pin_Z12_af[] = {
  //( 0, DAC     ,  0, OUT       , DAC0    ), // DAC0_OUT
  //( 0, CMP     ,  1, IN3       , CMP1    ), // CMP1_IN3
  AF( 0, ADC     ,  0, SE23      , ADC0    ), // ADC0_SE23
  //( 1, PTZ     , 12,           , PTZ12   ), // PTZ12
};

const pin_obj_t pin_Z12 = PIN(Z, 12, 1, pin_Z12_af);

const pin_af_obj_t pin_Z13_af[] = {
  //( 0, DAC     ,  1, OUT       , DAC1    ), // DAC1_OUT
  //( 0, CMP     ,  0, IN4       , CMP0    ), // CMP0_IN4
  //( 0, CMP     ,  2, IN3       , CMP2    ), // CMP2_IN3
  AF( 0, ADC     ,  1, SE23      , ADC1    ), // ADC1_SE23
  //( 1, PTZ     , 13,           , PTZ13   ), // PTZ13
};

const pin_obj_t pin_Z13 = PIN(Z, 13, 1, pin_Z13_af);

const pin_af_obj_t pin_E24_af[] = {
  AF( 0, ADC     ,  0, SE17      , ADC0    ), // ADC0_SE17
  //( 1, PTE     , 24,           , PTE24   ), // PTE24
  AF( 3, UART    ,  4, TX        , UART4   ), // UART4_TX
  AF( 5, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
};

const pin_obj_t pin_E24 = PIN(E, 24, 3, pin_E24_af);

const pin_af_obj_t pin_E25_af[] = {
  AF( 0, ADC     ,  0, SE18      , ADC0    ), // ADC0_SE18
  //( 1, PTE     , 25,           , PTE25   ), // PTE25
  AF( 3, UART    ,  4, RX        , UART4   ), // UART4_RX
  AF( 5, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
};

const pin_obj_t pin_E25 = PIN(E, 25, 3, pin_E25_af);

// const pin_af_obj_t pin_E26_af[] = {
  //( 1, PTE     , 26,           , PTE26   ), // PTE26
  //( 2, ENET    ,  0, 1588_CLKIN, ENET    ), // ENET_1588_CLKIN
  //( 3, UART    ,  4, CTS_b     , UART4   ), // UART4_CTS_b
  //( 6, RTC     ,  0, CLKOUT    , RTC     ), // RTC_CLKOUT
  //( 7, USB     ,  0, CLKIN     , USB     ), // USB_CLKIN
// };

const pin_obj_t pin_E26 = PIN(E, 26, 0, NULL);

const pin_af_obj_t pin_A5_af[] = {
  //( 1, PTA     ,  5,           , PTA5    ), // PTA5
  //( 2, USB     ,  0, CLKIN     , USB     ), // USB_CLKIN
  AF( 3, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
  //( 4, RMII    ,  0, RXER      , RMII0   ), // RMII0_RXER
  //( 4, MII     ,  0, RXER      , MII0    ), // MII0_RXER
  //( 5, CMP     ,  2, OUT       , CMP2    ), // CMP2_OUT
  //( 6, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 7, JTAG    ,  0, TRST_b    , JTAG    ), // JTAG_TRST_b
};

const pin_obj_t pin_A5 = PIN(A, 5, 1, pin_A5_af);

const pin_af_obj_t pin_A12_af[] = {
  //( 0, CMP     ,  2, IN0       , CMP2    ), // CMP2_IN0
  //( 1, PTA     , 12,           , PTA12   ), // PTA12
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  1, CH0       , FTM1    ), // FTM1_CH0
  //( 4, RMII    ,  0, RXD1      , RMII0   ), // RMII0_RXD1
  //( 4, MII     ,  0, RXD1      , MII0    ), // MII0_RXD1
  AF( 5, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
  //( 6, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
  AF( 7, FTM     ,  1, QD_PHA    , FTM1    ), // FTM1_QD_PHA
};

const pin_obj_t pin_A12 = PIN(A, 12, 3, pin_A12_af);

const pin_af_obj_t pin_A13_af[] = {
  //( 0, CMP     ,  2, IN1       , CMP2    ), // CMP2_IN1
  //( 1, PTA     , 13,           , PTA13   ), // PTA13
  //( 1, LLWU    ,  0, P4        , LLWU    ), // LLWU_P4
  //( 2, CAN     ,  0, RX        , CAN0    ), // CAN0_RX
  AF( 3, FTM     ,  1, CH1       , FTM1    ), // FTM1_CH1
  //( 4, RMII    ,  0, RXD0      , RMII0   ), // RMII0_RXD0
  //( 4, MII     ,  0, RXD0      , MII0    ), // MII0_RXD0
  AF( 5, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
  //( 6, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  AF( 7, FTM     ,  1, QD_PHB    , FTM1    ), // FTM1_QD_PHB
};

const pin_obj_t pin_A13 = PIN(A, 13, 3, pin_A13_af);

const pin_af_obj_t pin_A14_af[] = {
  //( 1, PTA     , 14,           , PTA14   ), // PTA14
  //( 2, SPI     ,  0, PCS0      , SPI0    ), // SPI0_PCS0
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  //( 4, RMII    ,  0, CRS_DV    , RMII0   ), // RMII0_CRS_DV
  //( 4, MII     ,  0, RXDV      , MII0    ), // MII0_RXDV
  AF( 5, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
  //( 6, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 7, I2S     ,  0, TXD1      , I2S0    ), // I2S0_TXD1
};

const pin_obj_t pin_A14 = PIN(A, 14, 2, pin_A14_af);

const pin_af_obj_t pin_A15_af[] = {
  //( 1, PTA     , 15,           , PTA15   ), // PTA15
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  //( 4, RMII    ,  0, TXEN      , RMII0   ), // RMII0_TXEN
  //( 4, MII     ,  0, TXEN      , MII0    ), // MII0_TXEN
  //( 6, I2S     ,  0, RXD0      , I2S0    ), // I2S0_RXD0
};

const pin_obj_t pin_A15 = PIN(A, 15, 2, pin_A15_af);

// const pin_af_obj_t pin_A16_af[] = {
  //( 1, PTA     , 16,           , PTA16   ), // PTA16
  //( 2, SPI     ,  0, SOUT      , SPI0    ), // SPI0_SOUT
  //( 3, UART    ,  0, CTS_b     , UART0   ), // UART0_CTS_b
  //( 3, UART    ,  0, COL_b     , UART0   ), // UART0_COL_b
  //( 4, RMII    ,  0, TXD0      , RMII0   ), // RMII0_TXD0
  //( 4, MII     ,  0, TXD0      , MII0    ), // MII0_TXD0
  //( 6, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 7, I2S     ,  0, RXD1      , I2S0    ), // I2S0_RXD1
// };

const pin_obj_t pin_A16 = PIN(A, 16, 0, NULL);

const pin_af_obj_t pin_A17_af[] = {
  AF( 0, ADC     ,  1, SE17      , ADC1    ), // ADC1_SE17
  //( 1, PTA     , 17,           , PTA17   ), // PTA17
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  //( 4, RMII    ,  0, TXD1      , RMII0   ), // RMII0_TXD1
  //( 4, MII     ,  0, TXD1      , MII0    ), // MII0_TXD1
  //( 6, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
};

const pin_obj_t pin_A17 = PIN(A, 17, 1, pin_A17_af);

// const pin_af_obj_t pin_A26_af[] = {
  //( 1, PTA     , 26,           , PTA26   ), // PTA26
  //( 4, MII     ,  0, TXD3      , MII0    ), // MII0_TXD3
  //( 6, FB      ,  0, A27       , FB      ), // FB_A27
// };

const pin_obj_t pin_A26 = PIN(A, 26, 0, NULL);

// const pin_af_obj_t pin_A28_af[] = {
  //( 1, PTA     , 28,           , PTA28   ), // PTA28
  //( 4, MII     ,  0, TXER      , MII0    ), // MII0_TXER
  //( 6, FB      ,  0, A25       , FB      ), // FB_A25
// };

const pin_obj_t pin_A28 = PIN(A, 28, 0, NULL);

// const pin_af_obj_t pin_A29_af[] = {
  //( 1, PTA     , 29,           , PTA29   ), // PTA29
  //( 4, MII     ,  0, COL       , MII0    ), // MII0_COL
  //( 6, FB      ,  0, A24       , FB      ), // FB_A24
// };

const pin_obj_t pin_A29 = PIN(A, 29, 0, NULL);

const pin_af_obj_t pin_B0_af[] = {
  AF( 0, ADC     ,  0, SE8       , ADC0    ), // ADC0_SE8
  AF( 0, ADC     ,  1, SE8       , ADC1    ), // ADC1_SE8
  //( 1, PTB     ,  0,           , PTB0    ), // PTB0
  //( 1, LLWU    ,  0, P5        , LLWU    ), // LLWU_P5
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF( 3, FTM     ,  1, CH0       , FTM1    ), // FTM1_CH0
  //( 4, RMII    ,  0, MDIO      , RMII0   ), // RMII0_MDIO
  //( 4, MII     ,  0, MDIO      , MII0    ), // MII0_MDIO
  AF( 6, FTM     ,  1, QD_PHA    , FTM1    ), // FTM1_QD_PHA
};

const pin_obj_t pin_B0 = PIN(B, 0, 5, pin_B0_af);

const pin_af_obj_t pin_B1_af[] = {
  AF( 0, ADC     ,  0, SE9       , ADC0    ), // ADC0_SE9
  AF( 0, ADC     ,  1, SE9       , ADC1    ), // ADC1_SE9
  //( 1, PTB     ,  1,           , PTB1    ), // PTB1
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF( 3, FTM     ,  1, CH1       , FTM1    ), // FTM1_CH1
  //( 4, RMII    ,  0, MDC       , RMII0   ), // RMII0_MDC
  //( 4, MII     ,  0, MDC       , MII0    ), // MII0_MDC
  AF( 6, FTM     ,  1, QD_PHB    , FTM1    ), // FTM1_QD_PHB
};

const pin_obj_t pin_B1 = PIN(B, 1, 5, pin_B1_af);

const pin_af_obj_t pin_B2_af[] = {
  AF( 0, ADC     ,  0, SE12      , ADC0    ), // ADC0_SE12
  //( 1, PTB     ,  2,           , PTB2    ), // PTB2
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  //( 4, ENET    ,  0, 1588_TMR0 , ENET0   ), // ENET0_1588_TMR0
  //( 6, FTM     ,  0, FLT3      , FTM0    ), // FTM0_FLT3
};

const pin_obj_t pin_B2 = PIN(B, 2, 2, pin_B2_af);

const pin_af_obj_t pin_B3_af[] = {
  AF( 0, ADC     ,  0, SE13      , ADC0    ), // ADC0_SE13
  //( 1, PTB     ,  3,           , PTB3    ), // PTB3
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  //( 3, UART    ,  0, CTS_b     , UART0   ), // UART0_CTS_b
  //( 3, UART    ,  0, COL_b     , UART0   ), // UART0_COL_b
  //( 4, ENET    ,  0, 1588_TMR1 , ENET0   ), // ENET0_1588_TMR1
  //( 6, FTM     ,  0, FLT0      , FTM0    ), // FTM0_FLT0
};

const pin_obj_t pin_B3 = PIN(B, 3, 2, pin_B3_af);

const pin_af_obj_t pin_B4_af[] = {
  AF( 0, ADC     ,  1, SE10      , ADC1    ), // ADC1_SE10
  //( 1, PTB     ,  4,           , PTB4    ), // PTB4
  //( 4, ENET    ,  0, 1588_TMR2 , ENET0   ), // ENET0_1588_TMR2
  //( 6, FTM     ,  1, FLT0      , FTM1    ), // FTM1_FLT0
};

const pin_obj_t pin_B4 = PIN(B, 4, 1, pin_B4_af);

const pin_af_obj_t pin_B5_af[] = {
  AF( 0, ADC     ,  1, SE11      , ADC1    ), // ADC1_SE11
  //( 1, PTB     ,  5,           , PTB5    ), // PTB5
  //( 4, ENET    ,  0, 1588_TMR3 , ENET0   ), // ENET0_1588_TMR3
  //( 6, FTM     ,  2, FLT0      , FTM2    ), // FTM2_FLT0
};

const pin_obj_t pin_B5 = PIN(B, 5, 1, pin_B5_af);

const pin_af_obj_t pin_B10_af[] = {
  AF( 0, ADC     ,  1, SE14      , ADC1    ), // ADC1_SE14
  //( 1, PTB     , 10,           , PTB10   ), // PTB10
  //( 2, SPI     ,  1, PCS0      , SPI1    ), // SPI1_PCS0
  AF( 3, UART    ,  3, RX        , UART3   ), // UART3_RX
  //( 5, FB      ,  0, AD19      , FB      ), // FB_AD19
  //( 6, FTM     ,  0, FLT1      , FTM0    ), // FTM0_FLT1
};

const pin_obj_t pin_B10 = PIN(B, 10, 2, pin_B10_af);

const pin_af_obj_t pin_B11_af[] = {
  AF( 0, ADC     ,  1, SE15      , ADC1    ), // ADC1_SE15
  //( 1, PTB     , 11,           , PTB11   ), // PTB11
  AF( 2, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
  AF( 3, UART    ,  3, TX        , UART3   ), // UART3_TX
  //( 5, FB      ,  0, AD18      , FB      ), // FB_AD18
  //( 6, FTM     ,  0, FLT2      , FTM0    ), // FTM0_FLT2
};

const pin_obj_t pin_B11 = PIN(B, 11, 3, pin_B11_af);

const pin_af_obj_t pin_B16_af[] = {
  //( 1, PTB     , 16,           , PTB16   ), // PTB16
  //( 2, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  //( 4, FTM     ,  0, CLKIN0    , FTM     ), // FTM_CLKIN0
  //( 5, FB      ,  0, AD17      , FB      ), // FB_AD17
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
};

const pin_obj_t pin_B16 = PIN(B, 16, 1, pin_B16_af);

const pin_af_obj_t pin_B17_af[] = {
  //( 1, PTB     , 17,           , PTB17   ), // PTB17
  //( 2, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  //( 4, FTM     ,  0, CLKIN1    , FTM     ), // FTM_CLKIN1
  //( 5, FB      ,  0, AD16      , FB      ), // FB_AD16
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
};

const pin_obj_t pin_B17 = PIN(B, 17, 1, pin_B17_af);

const pin_af_obj_t pin_B18_af[] = {
  //( 1, PTB     , 18,           , PTB18   ), // PTB18
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  2, CH0       , FTM2    ), // FTM2_CH0
  //( 4, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 5, FB      ,  0, AD15      , FB      ), // FB_AD15
  AF( 6, FTM     ,  2, QD_PHA    , FTM2    ), // FTM2_QD_PHA
};

const pin_obj_t pin_B18 = PIN(B, 18, 2, pin_B18_af);

const pin_af_obj_t pin_B19_af[] = {
  //( 1, PTB     , 19,           , PTB19   ), // PTB19
  //( 2, CAN     ,  0, RX        , CAN0    ), // CAN0_RX
  AF( 3, FTM     ,  2, CH1       , FTM2    ), // FTM2_CH1
  //( 4, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  //( 5, FB      ,  0, OE_b      , FB      ), // FB_OE_b
  AF( 6, FTM     ,  2, QD_PHB    , FTM2    ), // FTM2_QD_PHB
};

const pin_obj_t pin_B19 = PIN(B, 19, 2, pin_B19_af);

// const pin_af_obj_t pin_B20_af[] = {
  //( 1, PTB     , 20,           , PTB20   ), // PTB20
  //( 2, SPI     ,  2, PCS0      , SPI2    ), // SPI2_PCS0
  //( 5, FB      ,  0, AD31      , FB      ), // FB_AD31
  //( 6, CMP     ,  0, OUT       , CMP0    ), // CMP0_OUT
// };

const pin_obj_t pin_B20 = PIN(B, 20, 0, NULL);

const pin_af_obj_t pin_B21_af[] = {
  //( 1, PTB     , 21,           , PTB21   ), // PTB21
  AF( 2, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
  //( 5, FB      ,  0, AD30      , FB      ), // FB_AD30
  //( 6, CMP     ,  1, OUT       , CMP1    ), // CMP1_OUT
};

const pin_obj_t pin_B21 = PIN(B, 21, 1, pin_B21_af);

// const pin_af_obj_t pin_B22_af[] = {
  //( 1, PTB     , 22,           , PTB22   ), // PTB22
  //( 2, SPI     ,  2, SOUT      , SPI2    ), // SPI2_SOUT
  //( 5, FB      ,  0, AD29      , FB      ), // FB_AD29
  //( 6, CMP     ,  2, OUT       , CMP2    ), // CMP2_OUT
// };

const pin_obj_t pin_B22 = PIN(B, 22, 0, NULL);

// const pin_af_obj_t pin_B23_af[] = {
  //( 1, PTB     , 23,           , PTB23   ), // PTB23
  //( 2, SPI     ,  2, SIN       , SPI2    ), // SPI2_SIN
  //( 3, SPI     ,  0, PCS5      , SPI0    ), // SPI0_PCS5
  //( 5, FB      ,  0, AD28      , FB      ), // FB_AD28
// };

const pin_obj_t pin_B23 = PIN(B, 23, 0, NULL);

const pin_af_obj_t pin_C0_af[] = {
  AF( 0, ADC     ,  0, SE14      , ADC0    ), // ADC0_SE14
  //( 1, PTC     ,  0,           , PTC0    ), // PTC0
  //( 2, SPI     ,  0, PCS4      , SPI0    ), // SPI0_PCS4
  //( 3, PDB     ,  0, EXTRG     , PDB0    ), // PDB0_EXTRG
  //( 4, USB     ,  0, SOF_OUT   , USB     ), // USB_SOF_OUT
  //( 5, FB      ,  0, AD14      , FB      ), // FB_AD14
  //( 6, I2S     ,  0, TXD1      , I2S0    ), // I2S0_TXD1
};

const pin_obj_t pin_C0 = PIN(C, 0, 1, pin_C0_af);

const pin_af_obj_t pin_C1_af[] = {
  AF( 0, ADC     ,  0, SE15      , ADC0    ), // ADC0_SE15
  //( 1, PTC     ,  1,           , PTC1    ), // PTC1
  //( 1, LLWU    ,  0, P6        , LLWU    ), // LLWU_P6
  //( 2, SPI     ,  0, PCS3      , SPI0    ), // SPI0_PCS3
  //( 3, UART    ,  1, RTS_b     , UART1   ), // UART1_RTS_b
  AF( 4, FTM     ,  0, CH0       , FTM0    ), // FTM0_CH0
  //( 5, FB      ,  0, AD13      , FB      ), // FB_AD13
  //( 6, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
};

const pin_obj_t pin_C1 = PIN(C, 1, 2, pin_C1_af);

const pin_af_obj_t pin_C2_af[] = {
  AF( 0, ADC     ,  0, SE4b      , ADC0    ), // ADC0_SE4b
  //( 0, CMP     ,  1, IN0       , CMP1    ), // CMP1_IN0
  //( 1, PTC     ,  2,           , PTC2    ), // PTC2
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  1, CTS_b     , UART1   ), // UART1_CTS_b
  AF( 4, FTM     ,  0, CH1       , FTM0    ), // FTM0_CH1
  //( 5, FB      ,  0, AD12      , FB      ), // FB_AD12
  //( 6, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
};

const pin_obj_t pin_C2 = PIN(C, 2, 2, pin_C2_af);

const pin_af_obj_t pin_C3_af[] = {
  //( 0, CMP     ,  1, IN1       , CMP1    ), // CMP1_IN1
  //( 1, PTC     ,  3,           , PTC3    ), // PTC3
  //( 1, LLWU    ,  0, P7        , LLWU    ), // LLWU_P7
  //( 2, SPI     ,  0, PCS1      , SPI0    ), // SPI0_PCS1
  AF( 3, UART    ,  1, RX        , UART1   ), // UART1_RX
  AF( 4, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
  //( 5, CLKOUT  ,  0,           , CLKOUT  ), // CLKOUT
  //( 6, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
};

const pin_obj_t pin_C3 = PIN(C, 3, 2, pin_C3_af);

const pin_af_obj_t pin_C4_af[] = {
  //( 1, PTC     ,  4,           , PTC4    ), // PTC4
  //( 1, LLWU    ,  0, P8        , LLWU    ), // LLWU_P8
  //( 2, SPI     ,  0, PCS0      , SPI0    ), // SPI0_PCS0
  AF( 3, UART    ,  1, TX        , UART1   ), // UART1_TX
  AF( 4, FTM     ,  0, CH3       , FTM0    ), // FTM0_CH3
  //( 5, FB      ,  0, AD11      , FB      ), // FB_AD11
  //( 6, CMP     ,  1, OUT       , CMP1    ), // CMP1_OUT
};

const pin_obj_t pin_C4 = PIN(C, 4, 2, pin_C4_af);

const pin_af_obj_t pin_C5_af[] = {
  //( 1, PTC     ,  5,           , PTC5    ), // PTC5
  //( 1, LLWU    ,  0, P9        , LLWU    ), // LLWU_P9
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  //( 3, LPTMR   ,  0, ALT2      , LPTMR0  ), // LPTMR0_ALT2
  //( 4, I2S     ,  0, RXD0      , I2S0    ), // I2S0_RXD0
  //( 5, FB      ,  0, AD10      , FB      ), // FB_AD10
  //( 6, CMP     ,  0, OUT       , CMP0    ), // CMP0_OUT
  AF( 7, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
};

const pin_obj_t pin_C5 = PIN(C, 5, 2, pin_C5_af);

// const pin_af_obj_t pin_C6_af[] = {
  //( 0, CMP     ,  0, IN0       , CMP0    ), // CMP0_IN0
  //( 1, PTC     ,  6,           , PTC6    ), // PTC6
  //( 1, LLWU    ,  0, P10       , LLWU    ), // LLWU_P10
  //( 2, SPI     ,  0, SOUT      , SPI0    ), // SPI0_SOUT
  //( 3, PDB     ,  0, EXTRG     , PDB0    ), // PDB0_EXTRG
  //( 4, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 5, FB      ,  0, AD9       , FB      ), // FB_AD9
  //( 6, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
// };

const pin_obj_t pin_C6 = PIN(C, 6, 0, NULL);

// const pin_af_obj_t pin_C7_af[] = {
  //( 0, CMP     ,  0, IN1       , CMP0    ), // CMP0_IN1
  //( 1, PTC     ,  7,           , PTC7    ), // PTC7
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  //( 3, USB     ,  0, SOF_OUT   , USB     ), // USB_SOF_OUT
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD8       , FB      ), // FB_AD8
// };

const pin_obj_t pin_C7 = PIN(C, 7, 0, NULL);

const pin_af_obj_t pin_C8_af[] = {
  AF( 0, ADC     ,  1, SE4b      , ADC1    ), // ADC1_SE4b
  //( 0, CMP     ,  0, IN2       , CMP0    ), // CMP0_IN2
  //( 1, PTC     ,  8,           , PTC8    ), // PTC8
  AF( 3, FTM     ,  3, CH4       , FTM3    ), // FTM3_CH4
  //( 4, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
  //( 5, FB      ,  0, AD7       , FB      ), // FB_AD7
};

const pin_obj_t pin_C8 = PIN(C, 8, 2, pin_C8_af);

const pin_af_obj_t pin_C9_af[] = {
  AF( 0, ADC     ,  1, SE5b      , ADC1    ), // ADC1_SE5b
  //( 0, CMP     ,  0, IN3       , CMP0    ), // CMP0_IN3
  //( 1, PTC     ,  9,           , PTC9    ), // PTC9
  AF( 3, FTM     ,  3, CH5       , FTM3    ), // FTM3_CH5
  //( 4, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 5, FB      ,  0, AD6       , FB      ), // FB_AD6
  //( 6, FTM     ,  2, FLT0      , FTM2    ), // FTM2_FLT0
};

const pin_obj_t pin_C9 = PIN(C, 9, 2, pin_C9_af);

const pin_af_obj_t pin_C10_af[] = {
  AF( 0, ADC     ,  1, SE6b      , ADC1    ), // ADC1_SE6b
  //( 1, PTC     , 10,           , PTC10   ), // PTC10
  AF( 2, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  AF( 3, FTM     ,  3, CH6       , FTM3    ), // FTM3_CH6
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD5       , FB      ), // FB_AD5
};

const pin_obj_t pin_C10 = PIN(C, 10, 3, pin_C10_af);

const pin_af_obj_t pin_C11_af[] = {
  AF( 0, ADC     ,  1, SE7b      , ADC1    ), // ADC1_SE7b
  //( 1, PTC     , 11,           , PTC11   ), // PTC11
  //( 1, LLWU    ,  0, P11       , LLWU    ), // LLWU_P11
  AF( 2, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  AF( 3, FTM     ,  3, CH7       , FTM3    ), // FTM3_CH7
  //( 4, I2S     ,  0, RXD1      , I2S0    ), // I2S0_RXD1
  //( 5, FB      ,  0, RW_b      , FB      ), // FB_RW_b
};

const pin_obj_t pin_C11 = PIN(C, 11, 3, pin_C11_af);

const pin_af_obj_t pin_D0_af[] = {
  //( 1, PTD     ,  0,           , PTD0    ), // PTD0
  //( 1, LLWU    ,  0, P12       , LLWU    ), // LLWU_P12
  //( 2, SPI     ,  0, PCS0      , SPI0    ), // SPI0_PCS0
  //( 3, UART    ,  2, RTS_b     , UART2   ), // UART2_RTS_b
  AF( 4, FTM     ,  3, CH0       , FTM3    ), // FTM3_CH0
  //( 5, FB      ,  0, ALE       , FB      ), // FB_ALE
  //( 5, FB      ,  0, CS1_b     , FB      ), // FB_CS1_b
  //( 5, FB      ,  0, TS_b      , FB      ), // FB_TS_b
};

const pin_obj_t pin_D0 = PIN(D, 0, 1, pin_D0_af);

const pin_af_obj_t pin_D1_af[] = {
  AF( 0, ADC     ,  0, SE5b      , ADC0    ), // ADC0_SE5b
  //( 1, PTD     ,  1,           , PTD1    ), // PTD1
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  //( 3, UART    ,  2, CTS_b     , UART2   ), // UART2_CTS_b
  AF( 4, FTM     ,  3, CH1       , FTM3    ), // FTM3_CH1
  //( 5, FB      ,  0, CS0_b     , FB      ), // FB_CS0_b
};

const pin_obj_t pin_D1 = PIN(D, 1, 3, pin_D1_af);

const pin_af_obj_t pin_D2_af[] = {
  //( 1, PTD     ,  2,           , PTD2    ), // PTD2
  //( 1, LLWU    ,  0, P13       , LLWU    ), // LLWU_P13
  //( 2, SPI     ,  0, SOUT      , SPI0    ), // SPI0_SOUT
  AF( 3, UART    ,  2, RX        , UART2   ), // UART2_RX
  AF( 4, FTM     ,  3, CH2       , FTM3    ), // FTM3_CH2
  //( 5, FB      ,  0, AD4       , FB      ), // FB_AD4
  AF( 7, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
};

const pin_obj_t pin_D2 = PIN(D, 2, 3, pin_D2_af);

const pin_af_obj_t pin_D3_af[] = {
  //( 1, PTD     ,  3,           , PTD3    ), // PTD3
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  AF( 3, UART    ,  2, TX        , UART2   ), // UART2_TX
  AF( 4, FTM     ,  3, CH3       , FTM3    ), // FTM3_CH3
  //( 5, FB      ,  0, AD3       , FB      ), // FB_AD3
  AF( 7, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
};

const pin_obj_t pin_D3 = PIN(D, 3, 3, pin_D3_af);

const pin_af_obj_t pin_D4_af[] = {
  //( 1, PTD     ,  4,           , PTD4    ), // PTD4
  //( 1, LLWU    ,  0, P14       , LLWU    ), // LLWU_P14
  //( 2, SPI     ,  0, PCS1      , SPI0    ), // SPI0_PCS1
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  AF( 4, FTM     ,  0, CH4       , FTM0    ), // FTM0_CH4
  //( 5, FB      ,  0, AD2       , FB      ), // FB_AD2
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
  //( 7, SPI     ,  1, PCS0      , SPI1    ), // SPI1_PCS0
};

const pin_obj_t pin_D4 = PIN(D, 4, 1, pin_D4_af);

const pin_af_obj_t pin_D5_af[] = {
  AF( 0, ADC     ,  0, SE6b      , ADC0    ), // ADC0_SE6b
  //( 1, PTD     ,  5,           , PTD5    ), // PTD5
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  0, CTS_b     , UART0   ), // UART0_CTS_b
  //( 3, UART    ,  0, COL_b     , UART0   ), // UART0_COL_b
  AF( 4, FTM     ,  0, CH5       , FTM0    ), // FTM0_CH5
  //( 5, FB      ,  0, AD1       , FB      ), // FB_AD1
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
  AF( 7, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
};

const pin_obj_t pin_D5 = PIN(D, 5, 3, pin_D5_af);

const pin_af_obj_t pin_D6_af[] = {
  AF( 0, ADC     ,  0, SE7b      , ADC0    ), // ADC0_SE7b
  //( 1, PTD     ,  6,           , PTD6    ), // PTD6
  //( 1, LLWU    ,  0, P15       , LLWU    ), // LLWU_P15
  //( 2, SPI     ,  0, PCS3      , SPI0    ), // SPI0_PCS3
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  AF( 4, FTM     ,  0, CH6       , FTM0    ), // FTM0_CH6
  //( 5, FB      ,  0, AD0       , FB      ), // FB_AD0
  //( 6, FTM     ,  0, FLT0      , FTM0    ), // FTM0_FLT0
  //( 7, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
};

const pin_obj_t pin_D6 = PIN(D, 6, 3, pin_D6_af);

const pin_af_obj_t pin_D7_af[] = {
  //( 1, PTD     ,  7,           , PTD7    ), // PTD7
  //( 2, CMT     ,  0, IRO       , CMT     ), // CMT_IRO
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  AF( 4, FTM     ,  0, CH7       , FTM0    ), // FTM0_CH7
  //( 6, FTM     ,  0, FLT1      , FTM0    ), // FTM0_FLT1
  //( 7, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
};

const pin_obj_t pin_D7 = PIN(D, 7, 2, pin_D7_af);

const pin_af_obj_t pin_D8_af[] = {
  //( 1, PTD     ,  8,           , PTD8    ), // PTD8
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF( 3, UART    ,  5, RX        , UART5   ), // UART5_RX
  //( 6, FB      ,  0, A16       , FB      ), // FB_A16
};

const pin_obj_t pin_D8 = PIN(D, 8, 2, pin_D8_af);

const pin_af_obj_t pin_D9_af[] = {
  //( 1, PTD     ,  9,           , PTD9    ), // PTD9
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF( 3, UART    ,  5, TX        , UART5   ), // UART5_TX
  //( 6, FB      ,  0, A17       , FB      ), // FB_A17
};

const pin_obj_t pin_D9 = PIN(D, 9, 2, pin_D9_af);

// const pin_af_obj_t pin_D11_af[] = {
  //( 1, PTD     , 11,           , PTD11   ), // PTD11
  //( 2, SPI     ,  2, PCS0      , SPI2    ), // SPI2_PCS0
  //( 3, UART    ,  5, CTS_b     , UART5   ), // UART5_CTS_b
  //( 4, SDHC    ,  0, CLKIN     , SDHC0   ), // SDHC0_CLKIN
  //( 6, FB      ,  0, A19       , FB      ), // FB_A19
// };

const pin_obj_t pin_D11 = PIN(D, 11, 0, NULL);

const pin_af_obj_t pin_D12_af[] = {
  //( 1, PTD     , 12,           , PTD12   ), // PTD12
  AF( 2, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
  //( 3, FTM     ,  3, FLT0      , FTM3    ), // FTM3_FLT0
  //( 4, SDHC    ,  0, D4        , SDHC0   ), // SDHC0_D4
  //( 6, FB      ,  0, A20       , FB      ), // FB_A20
};

const pin_obj_t pin_D12 = PIN(D, 12, 1, pin_D12_af);

// const pin_af_obj_t pin_D13_af[] = {
  //( 1, PTD     , 13,           , PTD13   ), // PTD13
  //( 2, SPI     ,  2, SOUT      , SPI2    ), // SPI2_SOUT
  //( 4, SDHC    ,  0, D5        , SDHC0   ), // SDHC0_D5
  //( 6, FB      ,  0, A21       , FB      ), // FB_A21
// };

const pin_obj_t pin_D13 = PIN(D, 13, 0, NULL);

// const pin_af_obj_t pin_D14_af[] = {
  //( 1, PTD     , 14,           , PTD14   ), // PTD14
  //( 2, SPI     ,  2, SIN       , SPI2    ), // SPI2_SIN
  //( 4, SDHC    ,  0, D6        , SDHC0   ), // SDHC0_D6
  //( 6, FB      ,  0, A22       , FB      ), // FB_A22
// };

const pin_obj_t pin_D14 = PIN(D, 14, 0, NULL);

// const pin_af_obj_t pin_D15_af[] = {
  //( 1, PTD     , 15,           , PTD15   ), // PTD15
  //( 2, SPI     ,  2, PCS1      , SPI2    ), // SPI2_PCS1
  //( 4, SDHC    ,  0, D7        , SDHC0   ), // SDHC0_D7
  //( 6, FB      ,  0, A23       , FB      ), // FB_A23
// };

const pin_obj_t pin_D15 = PIN(D, 15, 0, NULL);

STATIC const mp_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_E0), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E1), (mp_obj_t)&pin_E1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E2), (mp_obj_t)&pin_E2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E3), (mp_obj_t)&pin_E3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E4), (mp_obj_t)&pin_E4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E5), (mp_obj_t)&pin_E5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E10), (mp_obj_t)&pin_E10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E11), (mp_obj_t)&pin_E11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z1), (mp_obj_t)&pin_Z1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z3), (mp_obj_t)&pin_Z3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z7), (mp_obj_t)&pin_Z7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z8), (mp_obj_t)&pin_Z8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z12), (mp_obj_t)&pin_Z12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z13), (mp_obj_t)&pin_Z13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E24), (mp_obj_t)&pin_E24 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E25), (mp_obj_t)&pin_E25 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E26), (mp_obj_t)&pin_E26 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A12), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A13), (mp_obj_t)&pin_A13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A14), (mp_obj_t)&pin_A14 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A15), (mp_obj_t)&pin_A15 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A16), (mp_obj_t)&pin_A16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A17), (mp_obj_t)&pin_A17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A26), (mp_obj_t)&pin_A26 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A28), (mp_obj_t)&pin_A28 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A29), (mp_obj_t)&pin_A29 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B0), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B1), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B2), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B3), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B4), (mp_obj_t)&pin_B4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B5), (mp_obj_t)&pin_B5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B10), (mp_obj_t)&pin_B10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B11), (mp_obj_t)&pin_B11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B16), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B17), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B18), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B19), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B20), (mp_obj_t)&pin_B20 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B21), (mp_obj_t)&pin_B21 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B22), (mp_obj_t)&pin_B22 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B23), (mp_obj_t)&pin_B23 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C0), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C1), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C2), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C3), (mp_obj_t)&pin_C3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C4), (mp_obj_t)&pin_C4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C5), (mp_obj_t)&pin_C5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C6), (mp_obj_t)&pin_C6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C7), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C8), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C9), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C10), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C11), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D0), (mp_obj_t)&pin_D0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D2), (mp_obj_t)&pin_D2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D4), (mp_obj_t)&pin_D4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D6), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D7), (mp_obj_t)&pin_D7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D8), (mp_obj_t)&pin_D8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D9), (mp_obj_t)&pin_D9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D11), (mp_obj_t)&pin_D11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D12), (mp_obj_t)&pin_D12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D13), (mp_obj_t)&pin_D13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D14), (mp_obj_t)&pin_D14 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D15), (mp_obj_t)&pin_D15 },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_D0), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D2), (mp_obj_t)&pin_D0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D4), (mp_obj_t)&pin_A13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D6), (mp_obj_t)&pin_D4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D7), (mp_obj_t)&pin_D2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D8), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D9), (mp_obj_t)&pin_C3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D10), (mp_obj_t)&pin_C4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D11), (mp_obj_t)&pin_C6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D12), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D13), (mp_obj_t)&pin_C5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D14), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D15), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D16), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D17), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D18), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D19), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D20), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D21), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D22), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D23), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D24), (mp_obj_t)&pin_E26 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D25), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D26), (mp_obj_t)&pin_A14 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D27), (mp_obj_t)&pin_A15 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D28), (mp_obj_t)&pin_A16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D29), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D30), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D31), (mp_obj_t)&pin_B10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D32), (mp_obj_t)&pin_B11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D33), (mp_obj_t)&pin_E24 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D34), (mp_obj_t)&pin_E25 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D35), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D36), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D37), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D38), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D39), (mp_obj_t)&pin_A17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D40), (mp_obj_t)&pin_A28 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D41), (mp_obj_t)&pin_A29 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D42), (mp_obj_t)&pin_A26 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D43), (mp_obj_t)&pin_B20 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D44), (mp_obj_t)&pin_B22 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D45), (mp_obj_t)&pin_B23 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D46), (mp_obj_t)&pin_B21 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D47), (mp_obj_t)&pin_D8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D48), (mp_obj_t)&pin_D9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D49), (mp_obj_t)&pin_B4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D50), (mp_obj_t)&pin_B5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D51), (mp_obj_t)&pin_D14 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D52), (mp_obj_t)&pin_D13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D53), (mp_obj_t)&pin_D12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D54), (mp_obj_t)&pin_D15 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D55), (mp_obj_t)&pin_D11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D56), (mp_obj_t)&pin_E10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D57), (mp_obj_t)&pin_E11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D58), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D59), (mp_obj_t)&pin_E1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D60), (mp_obj_t)&pin_E2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D61), (mp_obj_t)&pin_E3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D62), (mp_obj_t)&pin_E4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D63), (mp_obj_t)&pin_E5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A0), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A1), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A2), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A3), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A4), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A6), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A7), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A8), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A9), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A10), (mp_obj_t)&pin_Z7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A11), (mp_obj_t)&pin_Z8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A12), (mp_obj_t)&pin_B10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A13), (mp_obj_t)&pin_B11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A14), (mp_obj_t)&pin_E24 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A15), (mp_obj_t)&pin_E25 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A18), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A19), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A20), (mp_obj_t)&pin_A17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A21), (mp_obj_t)&pin_Z12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A22), (mp_obj_t)&pin_Z13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A23), (mp_obj_t)&pin_B4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A24), (mp_obj_t)&pin_B5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A25), (mp_obj_t)&pin_Z1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A26), (mp_obj_t)&pin_Z3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_LED), (mp_obj_t)&pin_C5 },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);
